stages:
  - npm-dependencies
  - build
  - test
  - sonarqube
  - deploy

tag_checker:
  stage: build
  script:
    - python tag_checker.py $CI_COMMIT_TAG
  only:
    - tags

npm-install:
  stage: npm-dependencies
  cache:
    key: node-modules
    paths:
      - frontend/node_modules
  script:
    - cd frontend
    - npm install

junit:
  stage: test
  script:
    - cd backend
    - ./gradlew test

# Run acceptance (cucumber) tests
# Uncomment after ATDD workshop (at the latest)
# cucumber:
#   stage: test
#   script:
#     - cd backend
#     - ./gradlew cucumber

# Run Jest (Javascript) tests
# Uncomment after Jest workshop (at the latest)
# jest:
#   stage: test
#   cache:
#     key: node-modules
#     paths:
#       - frontend/node_modules
#     policy: pull
#   script:
#     - cd frontend
#     - npm run test

# Export sonarqube (static code analysis) reports
# Uncomment after ATDD workshop (at the latest)
# dev-sonarqube:
#   stage: sonarqube
#   cache:
#     key: node-modules
#     paths:
#       - frontend/node_modules
#     policy: pull
#   script:
#     - cd frontend
#     - npm run sonarqube
#     - cd ../backend
#     - ./gradlew sonarqube
#   only:
#     - dev

# builds all branches, except dev and master
branch-build:
  stage: build
  cache:
    key: node-modules
    paths:
      - frontend/node_modules
    policy: pull
  script:
    - cd frontend
    - npm run build
    - cd ../backend
    - ./gradlew bootJar
  artifacts:
    paths:
      - frontend/dist
      - backend/build/libs
  except:
    - tags
    - master
    - dev

deploy-staging-backend:
  stage: deploy
  script:
    - cd backend
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/staging-backend/ || true
    - mkdir /home/gitlab-runner/staging-backend/
    - cp -r ./build/libs /home/gitlab-runner/staging-backend
    - cp ../runner/staging-backend.sh /home/gitlab-runner/staging-backend.sh
    - chmod u+x /home/gitlab-runner/staging-backend.sh
    - sudo systemctl restart seng302-staging-backend
  artifacts:
    paths:
      - backend/build/libs
  only:
    - dev

deploy-staging-frontend:
  stage: deploy
  cache:
    key: node-modules
    paths:
      - frontend/node_modules
    policy: pull
  script:
    - cd frontend
    - npm run build
    - rm -rf /home/gitlab-runner/staging-frontend/ || true
    - mkdir /home/gitlab-runner/staging-frontend/
    - cp -r ./dist/ /home/gitlab-runner/staging-frontend
    - cp ../runner/staging-frontend.sh /home/gitlab-runner/staging-frontend.sh
    - chmod u+x /home/gitlab-runner/staging-frontend.sh
    - sudo systemctl restart seng302-staging-frontend
  artifacts:
    paths:
      - frontend/dist
  only:
    - dev

deploy-production-backend:
  stage: deploy
  script:
    - cd backend
    - ./gradlew bootJar
    - rm -rf /home/gitlab-runner/production-backend/ || true
    - mkdir /home/gitlab-runner/production-backend/
    - cp -r ./build/libs /home/gitlab-runner/production-backend
    - cp ../runner/production-backend.sh /home/gitlab-runner/production-backend.sh
    - chmod u+x /home/gitlab-runner/production-backend.sh
    - sudo systemctl restart seng302-production-backend
  artifacts:
    paths:
      - backend/build/libs
  only:
    - tags
    - master

deploy-production-frontend:
  stage: deploy
  cache:
    key: node-modules
    paths:
      - frontend/node_modules
    policy: pull
  script:
    - cd frontend
    - npm run build-prod
    - rm -rf /home/gitlab-runner/production-frontend/ || true
    - mkdir /home/gitlab-runner/production-frontend/
    - cp -r ./dist/ /home/gitlab-runner/production-frontend
    - cp ../runner/production-frontend.sh /home/gitlab-runner/production-frontend.sh
    - chmod u+x /home/gitlab-runner/production-frontend.sh
    - sudo systemctl restart seng302-production-frontend
  artifacts:
    paths:
      - frontend/dist
  only:
    - tags
    - master
